### ISSUE TITLE
Integration invertal for Gauss-Laguerre

### ISSUE THREAD

**Issue by martenlienen** [billmclean/GaussQuadrature.jl#1]
Hi,
is the integration interval for Gauss-Laguerre in [the documentation](https://github.com/billmclean/GaussQuadrature.jl/blob/d53d92eecf86ca51d2457260d6b31f59f8b1fdb6/src/GaussQuadrature.jl#L41) supposed to be `0 < x < oo`? At least it says so in the [wikipedia article on it](https://en.wikipedia.org/wiki/Gauss%E2%80%93Laguerre_quadrature).

Regards,
Marten

**Comment by billmclean** [comment]
Hi Marten,
Thanks for raising this issue.  I have fixed it now.
Bill McLean.
On Sat, 2015-07-11 at 02:07 -0700, Marten Lienen wrote:

> Hi,
> is the integration interval for Gauss-Laguerre in the documentation
> supposed to be 0 < x < oo?
> Regards,
> Marten
> —
> 
> ## Reply to this email directly or view it on GitHub.
> 
> ---
> 
> A/Prof. William McLean                     tel: +61 2 9385 7045
> School of Mathematics and Statistics       fax: +61 2 9385 7123
> The University of New South Wales
> Sydney 2052                                email: w.mclean@unsw.edu.au
> AUSTRALIA                                  CRICOS Code for UNSW: 00098G

## Associate Editor, Journal of Integral Equations and Applications.

**Comment by martenlienen** [comment]
Thanks. Now it is not aligned anymore though ;)
