### ISSUE TITLE
Julia 1.0 uses v0.5.2 (which is broken) by default

### ISSUE THREAD

**Issue by sostock** [billmclean/GaussQuadrature.jl#13]
When adding GaussQuadrature in Julia 1.0, it will add version 0.5.2 (the latest version that is compatible with Julia 1.0). However, GaussQuadrature 0.5.2 doesn’t work due to a wrong compat entry for SpecialFunctions.

In my opinion, it would be best to remove version 0.5.2 from the General registry, so that users of Julia 1.0 will install version 0.5.0, which works. If you want, I can create a PR to remove GaussQuadrature 0.5.2 from the General registry.

**Comment by billmclean** [comment]
Am I correct in thinking that this change makes no difference to
anyone using later versions of Julia?  If so, I don't see any harm in
this change so you can go ahead and create the PR.

Would it  be better to fix the compat entry for SpecialFunctions?

On Wed, 2021-06-16 at 07:23 -0700, Sebastian Stock wrote:
> When adding GaussQuadrature in Julia 1.0, it will add version 0.5.2
> (the latest version that is compatible with Julia 1.0). However,
> GaussQuadrature 0.5.2 doesn’t work due to a wrong compat entry for
> SpecialFunctions.
> In my opinion, it would be best to remove version 0.5.2 from the
> General registry, so that users of Julia 1.0 will install version
> 0.5.0, which works. If you want, I can create a PR to remove
> GaussQuadrature 0.5.2 from the General registry.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
---------------------------------------------------------------------
A/Prof. William McLean                     tel: +61 2 9065 5254
School of Mathematics and Statistics       fax: +61 2 9385 7123
The University of New South Wales
Sydney 2052                                email: ***@***.***
AUSTRALIA                                  CRICOS Code for UNSW:
00098G
----------------------------------------------------------------------

**Comment by sostock** [comment]
Users of Julia ≥1.2 can use newer versions of GaussQuadrature, so only Julia 1.0 and 1.1 are affected.

Fixing the compat entry would be possible too. As far as I can tell, the only difference between fixing the compat entry and deleting GaussQuadrature 0.5.2 would be that the former would then use SpecialFunctions 0.8, while falling back to v0.5.0 would mean using SpecialFunctions 0.7.2. Therefore, I think it is better to fix the compat entry. I will make a PR to do that.

**Comment by sostock** [comment]
PR created: https://github.com/JuliaRegistries/General/pull/39111

**Comment by sostock** [comment]
Another possibility would be to remove 0.5.2 and relax the Julia compat entry for 0.5.3 to also accept Julia 1.0 and 1.1. GaussQuadrature 0.5.3 contains no changes other than fixing the SpecialFunctions compat entry and restricting Julia to versions ≥ 1.2.

**Comment by sostock** [comment]
The PR was merged. GaussQuadrature 0.5.2 now uses SpecialFunctions 0.8 and therefore doesn’t error anymore.
