### ISSUE TITLE
Allowing newer versions of SpecialFunctions.jl

### ISSUE THREAD

**Issue by mipals** [billmclean/GaussQuadrature.jl#14]
Hello,

The SpecialFunctions.jl got released as a version +2 a few months ago, which your `Project.toml` you do not seem to support. I wondered if that was by choice?

**Comment by billmclean** [comment]
Thanks for pointing this out.  I have updated the Project.toml to
permit SpecialFunctions 2.x.x.

On Sun, 2022-05-08 at 01:35 -0700, Mikkel Paltorp Schmitt wrote:
> Hello,
> The SpecialFunctions.jl got released as a version +2 a few months
> ago, which your Project.toml you do not seem to support. I wondered
> if that was by choice?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID:
> ***@***.***>

-- 
---------------------------------------------------------------------
A/Prof. William McLean                     tel: +61 2 9065 5254
School of Mathematics and Statistics       fax: +61 2 9385 7123
The University of New South Wales
Sydney 2052                                email: ***@***.***
AUSTRALIA                                  CRICOS Code for UNSW:00098G
----------------------------------------------------------------------

**Comment by mipals** [comment]
Perfect! Thanks a lot 😄
