### ISSUE TITLE
Tag for Julia 1.0

### ISSUE THREAD

**Issue by Godisemo** [billmclean/GaussQuadrature.jl#6]
This package seems to be compatible with Julia version 1.0 when checking out the master branch, but it is not properly tagged for regular installation. If you start with a fresh install of Julia 1.0 and run `add GaussQuadrature` you get version 0.4.0 of this package.

**Comment by billmclean** [comment]
Yes, I am still trying to get a new tag released (v0.4.2) properly.  I hope it will be sorted out soon.
