### ISSUE TITLE
Update Project.toml

### ISSUE THREAD

**Issue by RJDennis** [billmclean/GaussQuadrature.jl#7]
The Project.toml file has the version set to 0.5.2, but I believe that the latest tagged version is 0.5.3.  The updated version will not precompile and I think this might be the problem.

**Comment by billmclean** [comment]
If you look at Project.toml on github you will see that the version is 0.5.3.  Also,
https://github.com/JuliaRegistries/General/tree/master/G/GaussQuadrature shows the current version as 0.5.3. However, I don't know the correct way for a user to update a package now.  I finished up deleting .julia and installing again.
